### ISSUE TITLE
--app-datepicker-selected-year-color not working

### ISSUE THREAD

**Issue by panuhorsmalahti** [motss/app-datepicker#62] opened 2016-10-18 10:55 UTC
Hi, it doesn't seem like `--app-datepicker-selected-year-color` is working when a theme is not used. Also, the same seems to apply to `--app-datepicker-selected-year-bg`.

I believe  the reason is that these variables are not used here:
https://github.com/motss/app-datepicker/blob/master/app-datepicker.html#L304

They probably work with a theme (I haven't tested this, though):
https://github.com/motss/app-datepicker/blob/master/app-datepicker.html#L273
https://github.com/motss/app-datepicker/blob/master/app-datepicker.html#L498

My current workaround is using the mixin, which works:

```
    --app-datepicker-selected-year: {
        color: #000000;
    }
```

My proposed fix is to use these variables in line 304, but default to the values already used in the code.

**Comment by motss** [comment] 2016-10-21 13:13
@panuhorsmalahti The issue is confirmed. The patch is on its way with various fixes for some other issues.

Just a little update to the fix for this matter:

```patch
  div.each-list-of-years.is-selected {
    font-size: 24px;
    font-weight: 700;
+  color: var(--app-datepicker-selected-year-color, #009688);
+  background-color: var(--app-datepicker-selected-year-bg);

     @apply(--app-datepicker-selected-each-list-of-years);
}
```

**Closed** 2016-11-05 10:30 UTC
Labels: 1.x, enhancement, good-first-bug, in-progress, small-fix
