### ISSUE TITLE
Wrong September + October days before 1996

### ISSUE THREAD

**Issue by userquin** [motss/app-datepicker#87] opened 2017-06-12 11:05 UTC
### Description
Any year selected before 1996 shows September with 29 days and October with September 30 + October days (31). Also, September is shown in both cases, that is September for September and September also for October.

### Expected outcome

Any year must have 30 on September and 31 on October

### Actual outcome

![sep-1995](https://user-images.githubusercontent.com/6311119/27031218-aa57be42-4f6f-11e7-8e84-a1e2c411d6d1.png)
![oct-1995](https://user-images.githubusercontent.com/6311119/27031220-ac627c36-4f6f-11e7-80d7-4db746dedfef.png)
![sep-2005](https://user-images.githubusercontent.com/6311119/27031221-aef159ea-4f6f-11e7-9d75-5ee07942f7f0.png)
![oct-2005](https://user-images.githubusercontent.com/6311119/27031225-b1054e4e-4f6f-11e7-8377-92953e4b125e.png)

### Steps to reproduce

Go to demo page and select a year before 1996 and go to September and October

### Browsers Affected

- [ X] Chrome/ Opera
- [ X] Firefox
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [ ] IE 11

**Comment by userquin** [comment] 2017-06-12 11:40
On September 1995, 24th day appears twice...

**Comment by userquin** [comment] 2017-06-12 11:51
It seems there is a problem with Intl:

new window.Intl.DateTimeFormat('es-ES', { day: 'numeric' }).format(new Date(1995,8,24));
"24"
new window.Intl.DateTimeFormat('es-ES', { day: 'numeric' }).format(new Date(1995,8,25));
"24"
new window.Intl.DateTimeFormat('es-ES', { day: 'numeric' }).format(new Date(1995,8,26));
"25"
new window.Intl.DateTimeFormat('en-GB', { day: 'numeric' }).format(new Date(1995,8,24));
"24"
new window.Intl.DateTimeFormat('en-GB', { day: 'numeric' }).format(new Date(1995,8,25));
"24"
new window.Intl.DateTimeFormat('en-GB', { day: 'numeric' }).format(new Date(1995,8,26));
"25"
new window.Intl.DateTimeFormat('en-GB', { day: 'numeric' }).format(new Date(1996,8,26));
"26"
new window.Intl.DateTimeFormat('en-GB', { day: 'numeric' }).format(new Date(1996,8,25));
"25"
new window.Intl.DateTimeFormat('en-GB', { day: 'numeric' }).format(new Date(1996,8,24));
"24"

**Comment by motss** [comment] 2017-06-12 12:59
@userquin May I know which OS you're using?

**Comment by userquin** [comment] 2017-06-12 13:02
Windows 10 64 bits, also fails on javascript console on firefox and chrome

**Comment by motss** [comment] 2017-06-12 13:03
@userquin Really? I'm using Windows 10 x64 and never got this issue.

**Comment by userquin** [comment] 2017-06-12 13:03
new window.Intl.DateTimeFormat('es-AR', { month: 'short' }).format(new Date(1996,9,1));
"oct."
new window.Intl.DateTimeFormat('es-AR', { month: 'short' }).format(new Date(1995,9,1));
"sep."
new window.Intl.DateTimeFormat('es-AR', { month: 'short' }).format(new Date(1995,9,2));
"oct."

**Comment by userquin** [comment] 2017-06-12 13:04
just open current demo and go to a year before 1996 and select september and october

**Comment by motss** [comment] 2017-06-12 13:04
My result was `["oct.", "oct.", "oct."]`.

**Comment by userquin** [comment] 2017-06-12 13:07
Chrome Versión 58.0.3029.110 (64-bit)
Firefox 51.0.1 (32-bit)

**Comment by motss** [comment] 2017-06-12 13:08
@userquin Also confirmed that the datepicker from the demo. Everything shows up properly and unable to reproduce the error from what your screenshots have shown. 😢

**Comment by motss** [comment] 2017-06-12 13:09
@userquin Tested on Chrome 59. Shouldn't be a so much difference between Chrome 58 and Chrome 59. Would you mind trying it on Chrome 59?

**Comment by userquin** [comment] 2017-06-12 13:19
Also tested on chrome 59 but also failing... I can reproduce the problem in another dev PC but not in chrome android.
I only have intl-messageformat polyfill included, not DateTimeFormat polyfill...

**Comment by motss** [comment] 2017-06-12 13:41
@userquin On Chrome, you should not load any polyfill. Please refer to the table when to load polyfill on unsupported browsers: http://caniuse.com/#feat=internationalization.

Anyhow loading polyfill on browsers that natively support `Intl` will cause disastrous effect.

**Comment by userquin** [comment] 2017-06-12 13:47
I can also reproduce it on windows xp, but not in macosx (chrome).
I'll try to test at home on ubuntu 16 and centos (chrome and chrominum), windows 10 64 bits and macosx. 

The problem is that I can reproduce it on 2 windows 10 64 bits  a windows xp, via your component page demo...
The polyfill is loaded if necessary, it is loaded via app-localize-behavior.

**Comment by motss** [comment] 2017-06-12 13:50
@userquin This is very strange. Maybe take a look at the version of the `Intl` polyfill? I don't think `app-localize-behavior` will load a proper `Intl` polyfill. Can you confirm on that?

**Comment by userquin** [comment] 2017-06-12 13:58
I only navigate your component page, I'm not navigating my app. I can now reproduce it on 3 windows 10 64 bits at office, 2 dev PC and an administrative PC.
For example, selecting 1953 on your component page date picker, October is missing...

**Comment by userquin** [comment] 2017-06-12 14:04
Another 2 windows xp (chrome and firefox test) with the same problem...

**Comment by userquin** [comment] 2017-06-12 14:11
More info:

- Windows 10 Pro, v1607, compilation 14393.1198
- Windows Home, v1607, compilation 14393.447

**Comment by motss** [comment] 2017-06-12 14:26
@userquin I was able to reproduce something like what you faced when selecting any year before year 1983. I'm suspecting this could be a web platform issue.

**Comment by userquin** [comment] 2017-06-12 20:44
Also reproducible on macosx sierra (chrome and safari): March and April 1953 failing  on chrome and  September and October 1995 on Safari

**Comment by userquin** [comment] 2017-06-12 20:53
Also reproducible on ubuntu 16 (64 bits) (chrome, chromium and firefox): March and April 1953, all navigators failing.
Tomorrow I'll test on centos, but it seems it will have the same problem.

**Comment by userquin** [comment] 2017-06-12 21:03
It seems app-datepicker is not working on any browser on any operating system, I have tested with this results:

Windows XP, Windows 10 64 bits (home and professional): chrome and firefox not working
Macosx Sierra: chrome and safari not working
Linux Ubuntu 16 (64 bits): chrome, chromium and firefox not working.

Tomorrow at office I'll check chrome and firefox on centos and with an older version of macosx.

I'll check with my patch in #88 to see if not using UTC dates is the problem (presentation, logic seems to be ok).

**Comment by motss** [comment] 2017-06-13 13:38
This should be fixed in d00af1127e3c2743838403fe4fc870a2b9380f16. 👍

**Closed by motss** 2017-06-13 13:38 UTC
Labels: bug, chrome, firefox, good-first-bug, needs investigation
