### ISSUE TITLE
Switching months causes unexpected behavior in edge

### ISSUE THREAD

**Issue by kaseyhinton** [motss/app-datepicker#160] opened 2019-09-18 18:11 UTC
### Description
Changing months in edge causes the app-datepicker to behave strangely. Clicking next moves me september -> november. Clicking back to the previous month then takes me to a blank calendar.

```
 "lit-element": "^2.2.0",
 "app-datepicker": "^4.0.0-rc.30"
```

```
<app-datepicker
    firstdayofweek="0"
    showweeknumber="false"
    weeknumbertype="first-4-day-week"
    landscape="false"
    startview="calendar"
    min=""
    max=""
    value="2019-09-18"
    locale="en-US"
    disableddays=""
    disableddates=""
    weeklabel="Wk"
    dragratio="0.15">
</app-datepicker>
```

### Expected outcome
The month progresses in proper order on click or drag forward and backward.

### Actual outcome
The next month will occasionally get skipped and going backward shows a blank calendar. 

### Live Demo
![app-datepicker-edge-bug](https://user-images.githubusercontent.com/20712428/65173668-86f24d80-da0c-11e9-8af4-6b9ad1b69fb6.gif)

### Steps to reproduce
1. Install app-datepicker
2. Load polyfills copied from demo
3. Import app-datepicker on page copying config in the demo
4. Open in edge (non chromium version)

### Browsers Affected
- [ X] Edge 12+

Edge Browser Version
Microsoft Edge 44.18362.329.0

I tested in chrome and the chromium version of edge and did not see this problem.

**Comment by motss** [comment] 2019-09-30 15:12
@kaseyhinton First of all, thanks for reporting this bug happening on MS Edge. Was on vacation for the past few weeks. I'll take a look into this critical bug. I reckon this is caused by the Web Animation polyfill but need to dive deeper to find out the root cause.

**Comment by motss** [comment] 2020-01-13 15:59
@kaseyhinton Sorry for the delay. This should have been fixed in latest release.

**Comment by motss** [comment] 2020-01-13 16:00
Closing this.

**Closed by motss** 2020-01-13 16:00 UTC
Labels: bug, in-progress, lit-element, needs investigation
