### ISSUE TITLE
custom_typings.js is empty

### ISSUE THREAD

**Issue by maartenst** [motss/app-datepicker#182] opened 2020-06-06 12:03 UTC
### Description
the custom_typings.js file is empty and it makes es-dev-server fail with the following error: Loading failed for the module with source “http://dev.grootvakantiehuis.nl:9000/node_modules/app-datepicker/dist/custom_typings.js”.

### Expected outcome
no failure in loading this module

### Actual outcome
error in console: Loading failed for the module with source “http://dev.grootvakantiehuis.nl:9000/node_modules/app-datepicker/dist/custom_typings.js”

### Live Demo
none available

**Comment by motss** [comment] 2020-09-23 04:56
Thanks for reporting.

I also use `ev-dev-server` and never encounter such problem. Please find attached the screenshot not showing any error as stated in the ticket.

![Screenshot 2020-09-23 125529](https://user-images.githubusercontent.com/10607759/93968462-38545d80-fd9c-11ea-8ddc-d67b5a615df4.png)

**Comment by motss** [comment] 2020-09-23 04:57
Closing this as unable to reproduce

**Closed by motss** 2020-09-23 04:57 UTC
