### ISSUE TITLE
Not all years are displayed in the initial rendering in Firefox

### ISSUE THREAD

**Issue by panuhorsmalahti** [motss/app-datepicker#63] opened 2016-10-18 11:17 UTC
When the year selector is opened for the first time, only years up to 2016 are displayed. If the year is selected and opened again all the years are correctly displayed.

My initial guess is that it's somehow related to iron-list not picking up the proper size of the parent element. Note: if I close the inspector window all the years appear, probably due to the iron-list noticing a resize event / redrawing itself. Same happens if I open the year selector and then open the inspector window.

Screenshot of the issue:
![Image of the issue](http://i.imgur.com/8w2zv4f.png)

This issue only occurs on (at least the latest) Firefox, not Chrome.

**Comment by motss** [comment] 2016-10-21 12:29
@panuhorsmalahti Please state the FF and OS version that produces this problem. Tested on Windows 10 x64 FF 49.0.2 and couldn't reproduce.

**Comment by panuhorsmalahti** [comment] 2016-10-21 12:45
I'm testing on Mac OS X El Capitan and Firefox 49.0.2.

**Comment by motss** [comment] 2016-10-24 03:31
@panuhorsmalahti Tested on FF 49.0.2 on macOS Sierra but couldn't reproduce the issue. Any special steps to reproduce?

**Comment by panuhorsmalahti** [comment] 2016-10-24 09:03
Hmm, I can't reproduce this in jsfiddle ( https://jsfiddle.net/2q3fqehz/84/embedded/result/ ). I also noticed that if I call `window.wrap($0).fire('iron-resize');` after opening the year selection all the years become visible.

**Comment by motss** [comment] 2016-10-24 09:11
@panuhorsmalahti Hmm...a `fire('iron-resize')`seems fine for me. It's expected to run slow on unsupported browsers like FF as everything is still polyfill. However I still can't reproduce it.

**Comment by panuhorsmalahti** [comment] 2016-10-24 10:01
Argh, I didn't know GitHub spams this issue even from forks. I'm still testing a fix, disregard those for now.

**Comment by panuhorsmalahti** [comment] 2016-10-24 10:36
New clue: I can't reproduce this if I have animations enabled (by not using no-animation attribute).

**Comment by motss** [comment] 2017-03-20 15:05
Closing issue. Feel free to reopen.

**Closed by motss** 2017-03-20 15:05 UTC
Labels: 1.x, firefox, os-x, pending-response
