### ISSUE TITLE
paper-menu causes app-datepicker not to display properly

### ISSUE THREAD

**Issue by amanshu-kataria** [motss/app-datepicker#95] opened 2017-06-30 18:28 UTC
Paper-menu is causing app-datepicker not to display the calendar properly. 

![capture](https://user-images.githubusercontent.com/13014093/27749024-59b297f8-5def-11e7-9809-237ba06d7a61.PNG)

The calendar gets displayed properly before installing paper-menu, but after installing paper-menu the above issue occurs.

You can get an idea of how it look likes from the following links:
[Plunker Instance 1](https://embed.plnkr.co/uOuAGPc8oPKrnfY514PT/)
[Plunker Instance 2](https://embed.plnkr.co/IRfRJG9lOvPwBiQqSvbD/)

Though paper-menu is not being used in the above plunks but this how it is being displayed. There could be some other issue as well.

### Browsers Affected

- [x] Chrome/ Opera
- [x] Firefox
- [x] Edge 12+
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] IE 11

**Comment by amanshu-kataria** [comment] 2017-07-01 18:41
@motss Need some help please.

**Comment by motss** [comment] 2017-07-02 02:43
@amanshu-kataria Personally not really recommend to use `Polygit`. But I've tried to do it once locally and never encountered any issue so far.

**bower.json**

```json
{
  "name": "test-app-datepicker",
  "main": "test-app-datepicker.html",
  "dependencies": {
    "polymer": "Polymer/polymer#^2.0.0",
    "app-datepicker": "motss/app-datepicker#^2.11.0",
    "paper-listbox": "PolymerElements/paper-listbox#^2.0.0",
    "paper-item": "PolymerElements/paper-item#^2.0.0"
  },
  "devDependencies": {
    "iron-demo-helpers": "PolymerElements/iron-demo-helpers#^2.0.0",
    "web-component-tester": "Polymer/web-component-tester#^6.0.0",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0"
  },
  "resolutions": {
    "polymer": "^2.0.0"
  }
}
```

**test-app-datepicker.html**

```html
<link rel="import" href="../polymer/polymer-element.html">
<link rel="import" href="../app-datepicker/app-datepicker.html">
<link rel="import" href="../paper-item/paper-item.html">
<link rel="import" href="../paper-listbox/paper-listbox.html">

<dom-module id="test-app-datepicker">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <h2>Hello [[prop1]]!</h2>
    <app-datepicker></app-datepicker>

    <paper-listbox>
      <paper-item>Inbox</paper-item>
      <paper-item>Starred</paper-item>
      <paper-item>Sent mail</paper-item>
      <paper-item>Drafts</paper-item>
    </paper-listbox>
  </template>

  <script>
    /**
     * `test-app-datepicker`
     * 
     *
     * @customElement
     * @polymer
     * @demo demo/index.html
     */
    class TestAppDatepicker extends Polymer.Element {
      static get is() { return 'test-app-datepicker'; }
      static get properties() {
        return {
          prop1: {
            type: String,
            value: 'test-app-datepicker'
          }
        };
      }
    }

    window.customElements.define(TestAppDatepicker.is, TestAppDatepicker);
  </script>
</dom-module>
```

These are my recommendations:

1. Use [polymer-cli](https://github.com/Polymer/polymer-cli) to scaffold your element/ project.
2. Use the non-deprecated Polymer Elements. [paper-menu](https://github.com/PolymerElements/paper-menu) has been deprecated in favor of [paper-listbox](https://github.com/PolymerElements/paper-listbox) and that's why you never see a Polymer 2.0 ported version of `paper-menu`.
3. Be clear that which version of Polymer you are going to use. If you are gonna use either one, please ensure that all the elements you installed must have that support for that version of Polymer. You can also use both version of Polymer but again must ensure both version of Polymer must be installed properly. I personally **don't** recommend to to do that anyway.

Happy Polymer-ing! 🎉

**Comment by amanshu-kataria** [comment] 2017-07-02 17:52
@motss thanks for your recommendations.

I'm using Polymer 2 and here's the list of dependencies I'm using in my Polymer app:

**bower.json**
```
{
  "name": "test-app-datepicker",
  "main": "test-app-datepicker.html",
  "dependencies": {
    "polymer": "polymer/polymer#2.0.0",
    "platinum-sw": "PolymerElements/platinum-sw#^1.3.0",
    "app-layout": "PolymerElements/app-layout#^2.0.0",
    "paper-icon-button": "PolymerElements/paper-icon-button#^2.0.0",
    "paper-tooltip": "PolymerElements/paper-tooltip#^2.0.0",
    "paper-menu-button": "PolymerElements/paper-menu-button#^2.0.0",
    "iron-icons": "PolymerElements/iron-icons#^2.0.1",
    "paper-listbox": "PolymerElements/paper-listbox#^2.0.0",
    "paper-item": "PolymerElements/paper-item#^2.0.0",
    "paper-input": "PolymerElements/paper-input#^2.0.1",
    "paper-fab": "PolymerElements/paper-fab#^2.0.0",
    "moment": "^2.18.1",
    "moment-js": "^0.7.2",
    "paper-dialog": "PolymerElements/paper-dialog#^2.0.0",
    "paper-button": "PolymerElements/paper-button#^2.0.0",
    "paper-card": "PolymerElements/paper-card#^2.0.0",
    "iron-a11y-keys": "PolymerElements/iron-a11y-keys#^2.0.0",
    "app-notifications": "^1.0.0",
    "neon-animation": "PolymerElements/neon-animation#^2.0.1",
    "iron-localstorage": "PolymerElements/iron-localstorage#^2.0.0",
    "chrono": "^1.3.1",
    "paper-dialog-scrollable": "PolymerElements/paper-dialog-scrollable#^2.1.0",
    "app-datepicker": "motss/app-datepicker#^2.11.0"
  }
}
```

The above dependencies doesn't include `paper-menu`, which means it doesn't work even when `paper-menu` is not installed. But earlier `paper-menu` was also installed. Just noticed this thing.

**Comment by motss** [comment] 2017-07-03 01:15
Any error messages from the Dev Tools?

**Comment by amanshu-kataria** [comment] 2017-07-04 15:02
Getting the following errors:
![capture](https://user-images.githubusercontent.com/13014093/27835230-c9b1d0ae-60f7-11e7-8946-7a7c86588e4a.PNG)

**Comment by motss** [comment] 2017-07-04 15:28
@amanshu-kataria I see. This could be the cause. All these error messages are caused due to duplicated definition of certain components. I won't be able to tell what caused this errors and I will leave those for you to fix them. I believe the `app-datepicker` should work as expected once those errors go away.

**Comment by amanshu-kataria** [comment] 2017-07-05 09:09
@motss Thanks. I imported _polymer.html_ in _index.html_ which is not recommended, it was causing the above errors. Fixing those errors helped me, app-datepicker is now working.

**Comment by motss** [comment] 2017-07-05 12:16
Great. Closing this issue.

Thank you for sorting this issue out.

**Closed by motss** 2017-07-05 12:16 UTC
Labels: question
